name: On push to main branch

on:
  push:
    branches: [main]

jobs:
  generate-readme-and-prep-release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}

      - name: Generate README
        uses: momentohq/standards-and-practices/github-actions/generate-and-commit-oss-readme@gh-actions-v2
        with:
          project_status: official
          project_stability: beta
          project_type: sdk
          sdk_language: Elixir
          dev_docs_slug: elixir

      - name: Update release branch
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}
          path: src
          release-type: elixir
          package-name: client-sdk-elixir
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'

      - name: Publish test
        run: |
          echo "Published version: ${{ steps.release.outputs.src--tag_name }}"
        if: ${{ steps.release.outputs.src--release_created }}

#      - name: Publish to hex
#        env:
#          HEX_API_KEY: ${{ secrets.ELIXIR_HEX_PACKAGE_PUBLISH_API_KEY }}
#        run: |
#          pushd src
#            mix hex.publish --yes
#          popd
#        if: ${{ steps.release.outputs.src--release_created }}
